spring:
  application:
    name: user_service
  datasource:
    url: jdbc:h2:mem:caliber;Mode=Oracle
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_HOME}
server:
  port: 9085